
language: go

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u golang.org/x/lint/golint
  - export PATH=$PATH:$HOME/gopath/bin

script: go test ./...
